# ---------------------------------------------------------
# Plugin Name: CraftD3K
# Author: madetv1280
# Version: 2.0.0-release
# Description: Simple /craft plugin with permission support
# Copyright (c) 2025 madetv1280
# License: MIT-License https://mit-license.org/
# ---------------------------------------------------------

# Enable or disable the entire plugin
enabled: true  # [NOT YET IMPLEMENTED!]

# Cooldown between /craft or /c usage (in seconds)
# 0 means no cooldown
cooldown: 0
cooldown-message-enabled: true

# Path to messages file
messages-file: messages.yml

# Automatically check Modrinth for newer versions of this plugin
# Logs a message in the console if an update is available
check-for-update: true  # [NOT YET IMPLEMENTED!]

# Send anonymous usage statistics to bStats (no personal data)
# More info: https://bstats.org/getting-started
enable-bstats: true  # [NOT YET IMPLEMENTED!]
