# ---------------------------------------------------------
# Plugin Name: d3kCraft
# Author: madetv1280
# Version: 1.0.0-dev-003
# Description: Simple /craft Plugin with permission support
# Copyright (c) 2025 madetv1280
#
# License: MIT-License https://mit-license.org/
# ---------------------------------------------------------

# Enabled or disabled the WHOLE Plugin
enabled: true

craft-op-required: false

# cooldown between /craft or /c usage (in seconds) -1 means, no cooldown
cooldown: -1

cooldown-message-enabled: true

messages-file: messages.yml

# Automatically checks Modrinth for a newer version of this plugin and logs a message to the console if an update is available.
check-for-update: true

# Sending anonymous usage statistics to bStats (no personal data!)
# What data is collected? -> https://bstats.org/getting-started
enable-bstats: true;