name: CraftD3K
version: '2.0.0-release'
main: de.madetv1280.CraftD3K.Main
api-version: '1.21'
authors: [ madetv1280 ]
website: solo.to/madetv1280

commands:
  craft:
    description: Opens crafting menu
    usage: /<command>
  c:
    description: Alias /craft
    usage: /<command>
  craftreload:
    description: Reloads the Plugin
    usage: /<command>

permissions:
  craftd3k.craft.use:
    description: Permission for /craft
    default: true

  craftd3k.reload.use:
    description: Permission for /craftreload
    default: op

