name: d3kCraft
version: '1.0.0-dev-003'
main: de.madetv1280.d3kCraft.Main
api-version: '1.21'
authors: [ madetv1280 ]
website: solo.to/madetv1280

commands:
  craft:
    description: Opens crafting menu
    usage: /<command>
  c:
    description: Alias /craft
    usage: /<command>
  craftreload:
    description: Reloads the Plugin
    usage: /<command>

permissions:
  d3kcraft.craft.use:
    description: Permission for /craft
    default: true

  d3kcraft.reload.use:
    description: Permission for /craft
    default: op

